services:
  db_postgres_lily:
    image: postgres:latest
    container_name: postgres_db_1_lily
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_LILY}
    ports:
      - "5433:5432"
    networks:
      - lily_network


  db_postgres_da:
    image: postgres:latest
    container_name: postgres_db_2_da
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_DA}
    ports:
      - "5434:5432"
    networks:
      - lily_network


  db_postgres_bastina:
    image: postgres:latest
    container_name: postgres_db_3_bastina
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_BASTINA}
    ports:
      - "5435:5432"
    networks:
      - lily_network

  redis_lily_shop:
    image: redis
    hostname: redis
    container_name: redis_lily
    networks:
     - lily_network


  back_lily_shop:
    build: 
      context: ./back_drf
    ports:
      - '8001:8000'
    depends_on:
      - db_postgres_lily
      - db_postgres_da
      - db_postgres_bastina
      - redis_lily_shop
    volumes:
      - ./back_drf:/app
      - static_volume:/back_drf/lily_api/static
      - media_volume:/back_drf/lily_api/img
    container_name: django_lily
    networks:
     - lily_network
    env_file:
      - .env


  worker_1:
    build:
      context: ./back_drf
    hostname: worker
    entrypoint: celery
    container_name: celery_1
    volumes:
      - ./back_drf:/app
    depends_on:
      - redis_lily_shop
      - back_lily_shop
    working_dir: /app/lily_api
    env_file:
      - .env
    command: -A celery_app.app worker --loglevel=info
    networks:
     - lily_network


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
      certonly --webroot -w /var/www/certbot
      --force-renewal 
      --email canalofmoney2020@gmail.com 
#      -d lafleurlily.com
      -d dolceamorewine.com
      -d bastinawine.com
      --agree-tos

  vue_lily:
    build:
      context: ./vue_lily
      dockerfile: Dockerfile
    container_name: vue_lily
    ports: 
      - "80:80"
      - "443:443"

    restart: always
    depends_on:
      - back_lily_shop
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
     - lily_network
    env_file:
      - .env

  vue_da:
    build:
      context: ./vue_da
      dockerfile: Dockerfile
    container_name: vue_da
    ports: 
      - "80:80"
      - "443:443"

    restart: always
    depends_on:
      - back_lily_shop
    networks:
     - lily_network
    env_file:
      - .env

  vue_bastina:
    build:
      context: ./vue_bastina
      dockerfile: Dockerfile
    container_name: vue_bastina
    ports: 
      - "80:80"
      - "443:443"

    restart: always
    depends_on:
      - back_lily_shop
    networks:
     - lily_network
    env_file:
      - .env

nginx:
  image: nginx:latest
  container_name: nginx_proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - static_volume:/usr/share/nginx/html/static
    - media_volume:/usr/share/nginx/html/media
    - ./nginx/conf.d:/etc/nginx/conf.d # Custom Nginx configuration
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf  
    - ./certbot/conf:/etc/letsencrypt # SSL certificates
    - ./certbot/www:/var/www/certbot
    - ./lily_dist:/usr/share/nginx/html/lily # Serve files for lafleurlily
    - ./da_dist:/usr/share/nginx/html/da # Serve files for doclce amore
    - ./bastina_dist:/usr/share/nginx/html/bastina # Serve files for bastina
  depends_on:
    - vue_lily
    - vue_da
    - vue_bastina
  networks:
    - lily_network


volumes:
  static_volume:
  media_volume:


networks:
  lily_network: