services:
  db_lily_shop:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'lily_api'
      MYSQL_USER: 'admin'
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: 'admin5'
      MYSQL_ROOT_PASSWORD: 'password5'
    container_name: mysql_lily

  redis_lily_shop:
    image: redis
    hostname: redis
    container_name: redis_lily

  back_lily_shop:
    build: 
      context: ./back_drf
    ports:
      - '8001:8000'
    depends_on:
      - db_lily_shop
      - redis_lily_shop
    volumes:
      - ./back_drf:/app
      - static_volume:/back_drf/lily_api/static
      - media_volume:/back_drf/lily_api/img
    container_name: django_lily

  worker1:
    build:
      context: ./back_drf
    hostname: worker
    entrypoint: celery
    container_name: celery
    volumes:
      - ./back_drf:/app
    depends_on:
      - redis_lily_shop
      - back_lily_shop
    working_dir: /app/lily_api
    command: -A celery_app.app worker --loglevel=info
  
  vue_lily:
    build:
      context: ./vue_lily
      dockerfile: Dockerfile
    container_name: vue_lily
    ports: 
      - "8081:80"
    restart: always
    depends_on:
      - back_lily_shop
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media


volumes:
  static_volume:
  media_volume:

#  nginx:
#    image: nginx:1.26-alpine
#    ports:
#      - "81:80"
#    depends_on:
#      - vue_lily
#      - back_lily_shop
#    volumes:
#        - ./vue_lily/nginx/nginx.conf:/etc/nginx/nginx.conf
#        - ./vue_lily/nginx/conf.d:/etc/nginx/conf.d
#    container_name: nginx_lily

