services:
  db_postgres_lily:
    image: postgres:latest
    container_name: postgres_db_1_lily
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_LILY}
    ports:
      - "5433:5432"
    networks:
      - lily_network


  redis_lily_shop:
    image: redis
    hostname: redis
    container_name: redis_lily
    networks:
     - lily_network


  back_lily_shop:
    build:
      context: ./back_drf
    ports:
      - '8002:8000'
    depends_on:
      - db_postgres_lily
      - redis_lily_shop
    volumes:
      - ./back_drf:/app
      - static_volume:/back_drf/lily_api/static
      - media_volume:/back_drf/lily_api/img
    container_name: django_lily
    networks:
     - lily_network
    env_file:
      - .env


  worker_1:
    build:
      context: ./back_drf
    hostname: worker
    entrypoint: celery
    container_name: celery_1
    volumes:
      - ./back_drf:/app
    depends_on:
      - redis_lily_shop
      - back_lily_shop
    working_dir: /app/lily_api
    env_file:
      - .env
    command: -A celery_app.app worker --loglevel=info
    networks:
     - lily_network


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
     - ./certbot/conf:/etc/letsencrypt
     - ./certbot/www:/var/www/certbot
    command: >
      certonly --webroot -w /var/www/certbot
      --force-renewal
      --email canalofmoney2020@gmail.com
      -d lafleurlily.com
      --agree-tos
    networks:
     - lily_network


  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./nginx/conf.d:/etc/nginx/conf.d # Custom Nginx configuration
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt # SSL certificates
      - ./certbot/www:/var/www/certbot
    networks:
      - lily_network


volumes:
  static_volume:
  media_volume:


networks:
  lily_network:
