# renew_before_expiry = 30 days
version = 2.11.0
archive_dir = /etc/letsencrypt/archive/lafleurlily.com
cert = /etc/letsencrypt/live/lafleurlily.com/cert.pem
privkey = /etc/letsencrypt/live/lafleurlily.com/privkey.pem
chain = /etc/letsencrypt/live/lafleurlily.com/chain.pem
fullchain = /etc/letsencrypt/live/lafleurlily.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 2273262ac51c9b88741747ef98ad4d78
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
