name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH Deploy to Server
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no -tt ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd www/app/lafleurlily_shop
          git pull origin main 
          docker compose down
          docker compose build
          docker compose up db_postgres_lily -d
          sleep 5
          docker compose up redis_lily_shop -d
          docker compose up back_lily_shop -d
          docker compose up worker_1 -d
          docker compose up nginx -d
        EOF
